### ISSUE TITLE
Bug found in: installing by composer

### ISSUE THREAD

**Issue by marioquartz** [JordanRL/Roster#7]
When using 'composer require "samsara/roster:^0.1"' I have found that installation is not posible, because is required a private repository

The message is this:

```
  - Installing jetbrains/phpstorm-attributes (1.0): Cloning a7a83ae5df
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+d164b2fc805e+2021-07-08+0819
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden): 
```

And, of course, my personal token is not valid (I have to test it).
The action was realized using Docker 

As user of phpstorm I have interest in have support of my IDE.

**Comment by JordanRL** [comment]
This is interesting. I was able to run install in CI environments, so I didn't think this would be an issue. In any case, I've removed it as a dependency for now. It's not actually used at the moment and was included as part of samsara/mason (the docblock interpreter I wrote for this).

You should be able to run composer install or update now.

**Comment by marioquartz** [comment]
Roster is installed now. (Only have some problems with dealing with docker and composer) But now I have another bug using Roster XD

**Comment by JordanRL** [comment]
> Roster is installed now. (Only have some problems with dealing with docker and composer) But now I have another bug using Roster XD

Feel free to make another bug report! It always helps. :)
