### ISSUE TITLE
Bug found in: docs

### ISSUE THREAD

**Issue by SDanDyS** [JordanRL/Roster#9]
**Describe the bug**
The documentation seems to be off. It has `composer require-dev "samsara/roster:^0.1"`, but `require-dev` is not defined.

**To Reproduce**
Use composer with the following line: `composer require-dev "samsara/roster:^0.1"`.

**Expected behavior**
An error with the following message: 
`[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "require-dev" is not defined.`

**PHP Version**
PHP 8.0

**Additional context**
In the github documentation it says to use the following command for composer: `composer require "samsara/roster:^0.1"`.
In the docs in says to use the following command: `composer require-dev "samsara/roster:^0.1"` (which causes the error).

**Comment by JordanRL** [comment]
Oh hmm. I'll update this. The command should be this:

    composer --dev require "samsara/roster:^0.1"
